import { createContext, useContext, useState, useEffect, useCallback, useMemo, ReactNode } from "react";

type Language = "en" | "es" | "fr" | "pt" | "de" | "zh" | "ar" | "hi" | "yo";

interface Translations {
  [key: string]: string;
}

interface UserPreferences {
  preferredLanguage: Language;
  timezone: string;
  currency: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; name: string; nativeName: string }[];
  preferences: UserPreferences;
  updatePreferences: (prefs: Partial<UserPreferences>) => Promise<void>;
  supportedTimezones: string[];
  supportedCurrencies: string[];
}

const translations: Record<Language, Translations> = {
  en: {
    // Nav & common
    welcome: "Welcome to CHub",
    home: "Home",
    sermons: "Sermons",
    events: "Events",
    prayer: "Prayer",
    devotionals: "Devotionals",
    give: "Give",
    live: "Live",
    volunteer: "Volunteer",
    music: "Music",
    bible: "Bible Study",
    discipleship: "Discipleship",
    groups: "Groups",
    houseCells: "House Cells",
    media: "Media",
    community: "Community",
    login: "Login",
    logout: "Logout",
    dashboard: "Dashboard",
    admin: "Admin",
    members: "Members",
    attendance: "Attendance",
    analytics: "Analytics",
    messages: "Messages",
    profile: "Profile",
    settings: "Settings",
    search: "Search...",
    learnMore: "Learn More",
    serviceTimes: "Service Times",
    sundayService: "Sunday Service",
    wednesdayService: "Wednesday Service",
    fridayService: "Friday Service",
    location: "Location",
    contactUs: "Contact Us",
    aboutUs: "About Us",
    recentSermons: "Recent Sermons",
    upcomingEvents: "Upcoming Events",
    prayerRequests: "Prayer Requests",
    donate: "Donate",
    watchLive: "Watch Live",
    joinNow: "Join Now",
    readMore: "Read More",
    viewAll: "View All",
    viewAllEvents: "View All Events",
    viewPastEvents: "View Past Events",
    joinUsForFellowship: "Join us for fellowship and growth",
    noEvents: "No upcoming events",
    noSermons: "No sermons available",
    getStarted: "Get Started",
    myDashboard: "My Dashboard",
    adminDashboard: "Admin Dashboard",
    myAttendance: "My Attendance",
    privacy: "Privacy",
    signOut: "Sign out",
    loginToJoin: "Login to Join",
    feed: "Feed",

    // HomePage
    welcomeToCHub: "Welcome to CHub",
    experienceThe: "Experience the",
    powerOfFaith: "Power of Faith",
    heroDescription: "Join a vibrant community dedicated to loving God, loving people, and making a difference in our city and beyond.",
    planAVisit: "Plan a Visit",
    watchOnline: "Watch Online",
    checkIn: "Check In",
    membersCount: "Members",
    yearsActive: "Years Active",
    ministries: "Ministries",
    whatsHappening: "What's Happening",
    viewAllSmall: "View all",
    listenAndLearn: "Listen & Learn",
    latestSermons: "Latest Sermons",
    viewAllSermons: "View all sermons",
    getInvolved: "Get Involved",
    ourMinistries: "Our Ministries",
    ministriesDescription: "We have various ministries designed to help you grow in your faith and serve others",
    communityGroups: "Community Groups",
    communityGroupsDesc: "Connect with others in small groups for fellowship and growth",
    bibleStudy: "Bible Study",
    bibleStudyDesc: "Dive deeper into God's word with our weekly Bible study sessions",
    prayerMinistry: "Prayer Ministry",
    prayerMinistryDesc: "Join our prayer team and experience the power of prayer",
    visitUs: "Visit Us",
    visitUsThisSunday: "Visit Us This Sunday",
    visitUsDescription: "We welcome you to join us for worship, fellowship, and community. Experience the warmth of God's love at CHub.",
    getDirections: "Get Directions",

    // Login page
    welcomeBack: "Welcome back",
    createYourAccount: "Create your account",
    signInToAccount: "Sign in to your CHub account",
    joinOurCommunity: "Join our community today",
    fullName: "Full Name",
    emailAddress: "Email address",
    password: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign in",
    createAccount: "Create account",
    signingIn: "Signing in...",
    creatingAccount: "Creating account...",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUp: "Sign up",
    passwordMinLength: "Password must be at least 6 characters",
    welcomeBackTitle: "Welcome back!",
    accountCreated: "Account created!",
    signInSuccess: "You have successfully signed in.",
    accountCreatedSuccess: "Your account has been created successfully.",
    authError: "Authentication failed",
    joinCommunityDesc: "Join our vibrant community. Connect, grow, and serve together in faith.",

    // Events page
    eventsCalendar: "Events Calendar",
    eventsDescription: "Get involved and connect with others at one of our upcoming gatherings.",
    all: "All",
    allEvents: "All Events",
    noEventsFound: "No events found",
    checkBackSoon: "Check back soon for upcoming events!",
    calendarView: "Calendar View",
    categories: "Categories",
    hostSmallGroup: "Host a Small Group?",
    hostSmallGroupDesc: "We're always looking for new leaders to host community groups.",

    // Sermons page
    sermonLibrary: "Sermon Library",
    sermonsDescription: "Explore our collection of messages to help you grow in your faith journey.",
    aiSearch: "AI Search",
    forYou: "For You",
    smartSearch: "Smart Search",
    keywordSearch: "Keyword Search",
    searchByTopicPlaceholder: "Search by topic, title, keyword...",
    bibleVerse: "Bible Verse",
    topic: "Topic",
    selectTopic: "Select topic",
    clear: "Clear",
    recommendedForYou: "Recommended For You",
    noRecommendations: "No recommendations available yet.",
    searchByTitleOrPastor: "Search by title or pastor name...",
    status: "Status",
    allMessages: "All Messages",
    pastMessages: "Past Messages",
    upcomingMessages: "Upcoming Messages",
    series: "Series",
    allSeries: "All Series",
    speaker: "Speaker",
    allSpeakers: "All Speakers",
    noSermonsFound: "No sermons found",
    tryAdjustingSearch: "Try adjusting your search or filters",

    // Give page
    generosity: "Generosity",
    giveGenerously: "Give",
    generouslyHighlight: "Generously",
    giveVerse: "\"Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.\"",
    giveVerseRef: "2 Corinthians 9:7",
    campaigns: "Campaigns",
    history: "History",
    makeADonation: "Make a Donation",
    secureSimple: "Secure, simple, and impactful.",
    oneTime: "One-Time",
    recurring: "Recurring",
    customAmount: "Custom Amount ($)",
    processing: "Processing...",
    giveNow: "Now",
    monthly: "Monthly",
    secureEncryption: "Secure 256-bit SSL Encryption",
    whyWeGive: "Why We Give",
    whyWeGiveDesc: "Giving is an act of worship. It's a way to show God that He is first in our lives and to support the work He is doing through our church.",
    otherWaysToGive: "Other Ways to Give",
    textToGive: "Text \"GIVE\" to 555-1234",
    mailChecks: "Mail checks to 123 Faith Ave",
    sundayOffering: "Drop in offering buckets on Sunday",
    noCampaigns: "No active campaigns at the moment.",
    raised: "Raised",
    goal: "Goal",
    ends: "Ends",
    selected: "Selected",
    giveToCampaign: "Give to Campaign",
    loginToViewHistory: "Please log in to view your donation history.",
    noDonations: "You haven't made any donations yet.",
    donationHistory: "Your Donation History",
    thankYouGenerosity: "Thank you for your generosity!",
    completed: "Completed",
    thankYou: "Thank You!",
    donationSuccess: "Your generosity makes a difference.",
    donationError: "Could not process donation. Please try again.",

    // Prayer page
    prayerWall: "Prayer Wall",
    howCanWePray: "How Can We",
    prayForYou: "Pray",
    forYouPrayer: "For You?",
    prayerDescription: "Share your request with our community. We believe that prayer changes things.",
    noPrayerRequests: "No prayer requests found",

    // Footer
    quickLinks: "Quick Links",
    sermonArchive: "Sermon Archive",
    dailyDevotionals: "Daily Devotionals",
    waysToGive: "Ways to Give",
    tuesdayBibleStudy: "Tuesday Bible Study",
    thursdayPrayers: "Thursday Prayers",
    contact: "Contact",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    allRightsReserved: "All rights reserved.",
    footerDescription: "CHub - Your Church Management Solution. Helping churches connect, grow, and disciple their members.",
    discover: "Discover",
    error: "Error",
  },
  es: {
    welcome: "Bienvenido a CHub",
    home: "Inicio",
    sermons: "Predicas",
    events: "Eventos",
    prayer: "Oración",
    devotionals: "Devocionales",
    give: "Dar",
    live: "En Vivo",
    volunteer: "Voluntario",
    music: "Música",
    bible: "Estudio Bíblico",
    discipleship: "Discipulado",
    groups: "Grupos",
    houseCells: "Casas de Oración",
    media: "Media",
    community: "Comunidad",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    dashboard: "Panel",
    admin: "Admin",
    members: "Miembros",
    attendance: "Asistencia",
    analytics: "Analíticas",
    messages: "Mensajes",
    profile: "Perfil",
    settings: "Configuración",
    search: "Buscar...",
    learnMore: "Saber Más",
    serviceTimes: "Horarios de Servicio",
    sundayService: "Servicio del Domingo",
    wednesdayService: "Servicio del Miércoles",
    fridayService: "Servicio del Viernes",
    location: "Ubicación",
    contactUs: "Contáctenos",
    aboutUs: "Sobre Nosotros",
    recentSermons: "Predicas Recientes",
    upcomingEvents: "Próximos Eventos",
    prayerRequests: "Solicitudes de Oración",
    donate: "Donar",
    watchLive: "Ver En Vivo",
    joinNow: "Únete Ahora",
    readMore: "Leer Más",
    viewAll: "Ver Todo",
    viewAllEvents: "Ver Todos los Eventos",
    viewPastEvents: "Ver Eventos Pasados",
    joinUsForFellowship: "Únete a nosotros para comunión y crecimiento",
    noEvents: "No hay eventos próximos",
    noSermons: "No hay predicas disponibles",
    getStarted: "Comenzar",
    myDashboard: "Mi Panel",
    adminDashboard: "Panel de Admin",
    myAttendance: "Mi Asistencia",
    privacy: "Privacidad",
    signOut: "Cerrar Sesión",
    loginToJoin: "Iniciar Sesión para Unirse",
    feed: "Feed",

    // HomePage
    welcomeToCHub: "Bienvenido a CHub",
    experienceThe: "Experimenta el",
    powerOfFaith: "Poder de la Fe",
    heroDescription: "Únete a una comunidad vibrante dedicada a amar a Dios, amar a las personas y hacer la diferencia en nuestra ciudad y más allá.",
    planAVisit: "Planifica una Visita",
    watchOnline: "Ver en Línea",
    checkIn: "Registrarse",
    membersCount: "Miembros",
    yearsActive: "Años Activos",
    ministries: "Ministerios",
    whatsHappening: "Qué Está Pasando",
    viewAllSmall: "Ver todo",
    listenAndLearn: "Escucha y Aprende",
    latestSermons: "Últimas Predicas",
    viewAllSermons: "Ver todas las predicas",
    getInvolved: "Participa",
    ourMinistries: "Nuestros Ministerios",
    ministriesDescription: "Tenemos varios ministerios diseñados para ayudarte a crecer en tu fe y servir a otros",
    communityGroups: "Grupos Comunitarios",
    communityGroupsDesc: "Conéctate con otros en grupos pequeños para comunión y crecimiento",
    bibleStudy: "Estudio Bíblico",
    bibleStudyDesc: "Profundiza en la palabra de Dios con nuestras sesiones semanales de estudio bíblico",
    prayerMinistry: "Ministerio de Oración",
    prayerMinistryDesc: "Únete a nuestro equipo de oración y experimenta el poder de la oración",
    visitUs: "Visítanos",
    visitUsThisSunday: "Visítanos Este Domingo",
    visitUsDescription: "Te damos la bienvenida a unirte a nosotros para adoración, comunión y comunidad. Experimenta el calor del amor de Dios en CHub.",
    getDirections: "Obtener Direcciones",

    // Login
    welcomeBack: "Bienvenido de nuevo",
    createYourAccount: "Crea tu cuenta",
    signInToAccount: "Inicia sesión en tu cuenta CHub",
    joinOurCommunity: "Únete a nuestra comunidad hoy",
    fullName: "Nombre Completo",
    emailAddress: "Correo electrónico",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    signIn: "Iniciar sesión",
    createAccount: "Crear cuenta",
    signingIn: "Iniciando sesión...",
    creatingAccount: "Creando cuenta...",
    dontHaveAccount: "¿No tienes cuenta?",
    alreadyHaveAccount: "¿Ya tienes cuenta?",
    signUp: "Registrarse",
    passwordMinLength: "La contraseña debe tener al menos 6 caracteres",
    welcomeBackTitle: "¡Bienvenido de nuevo!",
    accountCreated: "¡Cuenta creada!",
    signInSuccess: "Has iniciado sesión exitosamente.",
    accountCreatedSuccess: "Tu cuenta ha sido creada exitosamente.",
    authError: "Error de autenticación",
    joinCommunityDesc: "Únete a nuestra vibrante comunidad. Conéctate, crece y sirve juntos en la fe.",

    // Events
    eventsCalendar: "Calendario de Eventos",
    eventsDescription: "Participa y conéctate con otros en una de nuestras próximas reuniones.",
    all: "Todos",
    allEvents: "Todos los Eventos",
    noEventsFound: "No se encontraron eventos",
    checkBackSoon: "¡Vuelve pronto para ver próximos eventos!",
    calendarView: "Vista de Calendario",
    categories: "Categorías",
    hostSmallGroup: "¿Organizar un Grupo Pequeño?",
    hostSmallGroupDesc: "Siempre estamos buscando nuevos líderes para organizar grupos comunitarios.",

    // Sermons
    sermonLibrary: "Biblioteca de Predicas",
    sermonsDescription: "Explora nuestra colección de mensajes para ayudarte a crecer en tu camino de fe.",
    aiSearch: "Búsqueda IA",
    forYou: "Para Ti",
    smartSearch: "Búsqueda Inteligente",
    keywordSearch: "Búsqueda por Palabra Clave",
    searchByTopicPlaceholder: "Buscar por tema, título, palabra clave...",
    bibleVerse: "Versículo Bíblico",
    topic: "Tema",
    selectTopic: "Seleccionar tema",
    clear: "Limpiar",
    recommendedForYou: "Recomendado Para Ti",
    noRecommendations: "No hay recomendaciones disponibles aún.",
    searchByTitleOrPastor: "Buscar por título o nombre del pastor...",
    status: "Estado",
    allMessages: "Todos los Mensajes",
    pastMessages: "Mensajes Pasados",
    upcomingMessages: "Próximos Mensajes",
    series: "Serie",
    allSeries: "Todas las Series",
    speaker: "Predicador",
    allSpeakers: "Todos los Predicadores",
    noSermonsFound: "No se encontraron predicas",
    tryAdjustingSearch: "Intenta ajustar tu búsqueda o filtros",

    // Give
    generosity: "Generosidad",
    giveGenerously: "Da",
    generouslyHighlight: "Generosamente",
    giveVerse: "\"Cada uno debe dar según lo que haya decidido en su corazón, no de mala gana ni por obligación, porque Dios ama al dador alegre.\"",
    giveVerseRef: "2 Corintios 9:7",
    campaigns: "Campañas",
    history: "Historial",
    makeADonation: "Hacer una Donación",
    secureSimple: "Seguro, simple y con impacto.",
    oneTime: "Una Vez",
    recurring: "Recurrente",
    customAmount: "Cantidad Personalizada ($)",
    processing: "Procesando...",
    giveNow: "Ahora",
    monthly: "Mensual",
    secureEncryption: "Encriptación SSL segura de 256 bits",
    whyWeGive: "Por Qué Damos",
    whyWeGiveDesc: "Dar es un acto de adoración. Es una forma de mostrar a Dios que Él es primero en nuestras vidas y apoyar la obra que está haciendo a través de nuestra iglesia.",
    otherWaysToGive: "Otras Formas de Dar",
    noCampaigns: "No hay campañas activas en este momento.",
    raised: "Recaudado",
    goal: "Meta",
    selected: "Seleccionado",
    giveToCampaign: "Dar a Campaña",
    loginToViewHistory: "Inicia sesión para ver tu historial de donaciones.",
    noDonations: "Aún no has hecho ninguna donación.",
    donationHistory: "Tu Historial de Donaciones",
    thankYouGenerosity: "¡Gracias por tu generosidad!",
    completed: "Completado",
    thankYou: "¡Gracias!",
    donationSuccess: "Tu generosidad hace la diferencia.",
    donationError: "No se pudo procesar la donación. Inténtalo de nuevo.",

    // Prayer
    prayerWall: "Muro de Oración",
    howCanWePray: "¿Cómo Podemos",
    prayForYou: "Orar",
    forYouPrayer: "Por Ti?",
    prayerDescription: "Comparte tu solicitud con nuestra comunidad. Creemos que la oración cambia las cosas.",

    // Footer
    quickLinks: "Enlaces Rápidos",
    sermonArchive: "Archivo de Predicas",
    dailyDevotionals: "Devocionales Diarios",
    waysToGive: "Formas de Dar",
    tuesdayBibleStudy: "Estudio Bíblico del Martes",
    thursdayPrayers: "Oraciones del Jueves",
    contact: "Contacto",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    allRightsReserved: "Todos los derechos reservados.",
    footerDescription: "CHub - Tu Solución de Gestión de Iglesia. Ayudando a las iglesias a conectar, crecer y discipular a sus miembros.",
    discover: "Descubrir",
    error: "Error",
  },
  fr: {
    welcome: "Bienvenue à CHub",
    home: "Accueil",
    sermons: "Prédications",
    events: "Événements",
    prayer: "Prière",
    devotionals: "Dévotions",
    give: "Donner",
    live: "En Direct",
    music: "Musique",
    bible: "Étude Biblique",
    discipleship: "Discipulat",
    login: "Connexion",
    logout: "Déconnexion",
    dashboard: "Tableau de Bord",
    admin: "Admin",
    members: "Membres",
    attendance: "Présence",
    analytics: "Analytiques",
    messages: "Messages",
    profile: "Profil",
    settings: "Paramètres",
    search: "Rechercher...",
    learnMore: "En Savoir Plus",
    serviceTimes: "Horaires des Services",
    sundayService: "Service de Dimanche",
    wednesdayService: "Service de Mercredi",
    location: "Emplacement",
    contactUs: "Contactez-nous",
    aboutUs: "À Propos",
    recentSermons: "Prédications Récentes",
    upcomingEvents: "Événements à Venir",
    prayerRequests: "Demandes de Prière",
    donate: "Faire un Don",
    watchLive: "Regarder en Direct",
    joinNow: "Rejoignez Maintenant",
    readMore: "Lire Plus",
    viewAll: "Voir Tout",
    viewAllEvents: "Voir Tous les Événements",
    viewPastEvents: "Voir les Événements Passés",
    joinUsForFellowship: "Rejoignez-nous pour communion et croissance",
    noEvents: "Pas d'événements à venir",
    noSermons: "Aucune prédication disponible",
    volunteer: "Bénévole",
    groups: "Groupes",
    houseCells: "Cellules de Maison",
    media: "Médias",
    community: "Communauté",
    getStarted: "Commencer",
    myDashboard: "Mon Tableau de Bord",
    adminDashboard: "Tableau de Bord Admin",
    myAttendance: "Ma Présence",
    privacy: "Confidentialité",
    signOut: "Se Déconnecter",
    feed: "Fil",

    welcomeToCHub: "Bienvenue à CHub",
    experienceThe: "Vivez la",
    powerOfFaith: "Puissance de la Foi",
    heroDescription: "Rejoignez une communauté dynamique dédiée à aimer Dieu, aimer les gens et faire la différence dans notre ville et au-delà.",
    planAVisit: "Planifier une Visite",
    watchOnline: "Regarder en Ligne",
    checkIn: "S'enregistrer",
    membersCount: "Membres",
    yearsActive: "Années d'Activité",
    ministries: "Ministères",
    whatsHappening: "Quoi de Neuf",
    viewAllSmall: "Voir tout",
    listenAndLearn: "Écouter et Apprendre",
    latestSermons: "Dernières Prédications",
    viewAllSermons: "Voir toutes les prédications",
    getInvolved: "Impliquez-vous",
    ourMinistries: "Nos Ministères",
    ministriesDescription: "Nous avons divers ministères conçus pour vous aider à grandir dans votre foi et à servir les autres",
    communityGroups: "Groupes Communautaires",
    communityGroupsDesc: "Connectez-vous avec d'autres dans de petits groupes pour la communion et la croissance",
    bibleStudy: "Étude Biblique",
    bibleStudyDesc: "Approfondissez la parole de Dieu avec nos séances d'étude biblique hebdomadaires",
    prayerMinistry: "Ministère de Prière",
    prayerMinistryDesc: "Rejoignez notre équipe de prière et expérimentez la puissance de la prière",
    visitUs: "Visitez-nous",
    visitUsThisSunday: "Visitez-nous Ce Dimanche",
    visitUsDescription: "Nous vous invitons à nous rejoindre pour l'adoration, la communion et la communauté.",
    getDirections: "Itinéraire",

    welcomeBack: "Bienvenue",
    createYourAccount: "Créez votre compte",
    signInToAccount: "Connectez-vous à votre compte CHub",
    joinOurCommunity: "Rejoignez notre communauté aujourd'hui",
    fullName: "Nom Complet",
    emailAddress: "Adresse e-mail",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié?",
    signIn: "Se connecter",
    createAccount: "Créer un compte",
    signingIn: "Connexion en cours...",
    creatingAccount: "Création du compte...",
    dontHaveAccount: "Pas de compte?",
    alreadyHaveAccount: "Déjà un compte?",
    signUp: "S'inscrire",
    passwordMinLength: "Le mot de passe doit contenir au moins 6 caractères",
    joinCommunityDesc: "Rejoignez notre communauté dynamique. Connectez, grandissez et servez ensemble dans la foi.",

    eventsCalendar: "Calendrier des Événements",
    eventsDescription: "Impliquez-vous et connectez-vous avec d'autres lors de nos prochains rassemblements.",
    all: "Tous",
    allEvents: "Tous les Événements",
    noEventsFound: "Aucun événement trouvé",
    checkBackSoon: "Revenez bientôt pour les prochains événements!",
    calendarView: "Vue Calendrier",
    categories: "Catégories",
    hostSmallGroup: "Animer un Petit Groupe?",
    hostSmallGroupDesc: "Nous cherchons toujours de nouveaux leaders pour animer des groupes communautaires.",

    sermonLibrary: "Bibliothèque de Prédications",
    sermonsDescription: "Explorez notre collection de messages pour grandir dans votre parcours de foi.",
    aiSearch: "Recherche IA",
    forYou: "Pour Vous",
    smartSearch: "Recherche Intelligente",
    keywordSearch: "Recherche par Mot-clé",
    noSermonsFound: "Aucune prédication trouvée",
    tryAdjustingSearch: "Essayez d'ajuster votre recherche ou vos filtres",

    generosity: "Générosité",
    giveGenerously: "Donnez",
    generouslyHighlight: "Généreusement",
    makeADonation: "Faire un Don",
    secureSimple: "Sécurisé, simple et impactant.",
    oneTime: "Ponctuel",
    recurring: "Récurrent",
    campaigns: "Campagnes",
    history: "Historique",

    prayerWall: "Mur de Prière",
    howCanWePray: "Comment Pouvons-nous",
    prayForYou: "Prier",
    forYouPrayer: "Pour Vous?",
    prayerDescription: "Partagez votre demande avec notre communauté. Nous croyons que la prière change les choses.",

    quickLinks: "Liens Rapides",
    sermonArchive: "Archive de Prédications",
    dailyDevotionals: "Dévotions Quotidiennes",
    waysToGive: "Façons de Donner",
    tuesdayBibleStudy: "Étude Biblique du Mardi",
    thursdayPrayers: "Prières du Jeudi",
    contact: "Contact",
    privacyPolicy: "Politique de Confidentialité",
    termsOfService: "Conditions d'Utilisation",
    allRightsReserved: "Tous droits réservés.",
    footerDescription: "CHub - Votre Solution de Gestion d'Église.",
    discover: "Découvrir",
    error: "Erreur",
  },
  pt: {
    welcome: "Bem-vindo ao CHub",
    home: "Início",
    sermons: "Pregações",
    events: "Eventos",
    prayer: "Oração",
    devotionals: "Devocionais",
    give: "Doar",
    live: "Ao Vivo",
    music: "Música",
    bible: "Estudo Bíblico",
    discipleship: "Discipulado",
    login: "Entrar",
    logout: "Sair",
    dashboard: "Painel",
    admin: "Admin",
    members: "Membros",
    attendance: "Presença",
    analytics: "Analíticos",
    messages: "Mensagens",
    profile: "Perfil",
    settings: "Configurações",
    search: "Pesquisar...",
    learnMore: "Saiba Mais",
    serviceTimes: "Horários de Serviço",
    sundayService: "Culto de Domingo",
    wednesdayService: "Culto de Quarta",
    location: "Localização",
    contactUs: "Fale Conosco",
    aboutUs: "Sobre Nós",
    recentSermons: "Pregações Recentes",
    upcomingEvents: "Próximos Eventos",
    prayerRequests: "Pedidos de Oração",
    donate: "Doar",
    watchLive: "Assistir ao Vivo",
    joinNow: "Participe Agora",
    readMore: "Ler Mais",
    viewAll: "Ver Tudo",
    viewAllEvents: "Ver Todos os Eventos",
    viewPastEvents: "Ver Eventos Passados",
    joinUsForFellowship: "Participe da nossa comunhão e crescimento",
    noEvents: "Nenhum evento próximo",
    noSermons: "Nenhuma pregação disponível",
    volunteer: "Voluntário",
    groups: "Grupos",
    houseCells: "Células",
    media: "Mídia",
    community: "Comunidade",
    getStarted: "Começar",
    myDashboard: "Meu Painel",
    adminDashboard: "Painel Admin",
    myAttendance: "Minha Presença",
    privacy: "Privacidade",
    signOut: "Sair",
    feed: "Feed",

    welcomeToCHub: "Bem-vindo ao CHub",
    experienceThe: "Experimente o",
    powerOfFaith: "Poder da Fé",
    heroDescription: "Junte-se a uma comunidade vibrante dedicada a amar a Deus, amar as pessoas e fazer a diferença.",
    planAVisit: "Planeje uma Visita",
    watchOnline: "Assistir Online",
    checkIn: "Check In",
    membersCount: "Membros",
    yearsActive: "Anos Ativos",
    ministries: "Ministérios",
    whatsHappening: "O Que Está Acontecendo",
    latestSermons: "Últimas Pregações",
    viewAllSermons: "Ver todas as pregações",
    getInvolved: "Participe",
    ourMinistries: "Nossos Ministérios",
    communityGroups: "Grupos Comunitários",
    bibleStudy: "Estudo Bíblico",
    prayerMinistry: "Ministério de Oração",
    visitUs: "Visite-nos",
    visitUsThisSunday: "Visite-nos Neste Domingo",
    getDirections: "Obter Direções",

    welcomeBack: "Bem-vindo de volta",
    createYourAccount: "Crie sua conta",
    signIn: "Entrar",
    createAccount: "Criar conta",
    signUp: "Registrar",
    fullName: "Nome Completo",
    emailAddress: "Endereço de e-mail",
    password: "Senha",
    forgotPassword: "Esqueceu a senha?",

    eventsCalendar: "Calendário de Eventos",
    all: "Todos",
    allEvents: "Todos os Eventos",
    sermonLibrary: "Biblioteca de Pregações",
    generosity: "Generosidade",
    giveGenerously: "Doe",
    generouslyHighlight: "Generosamente",
    makeADonation: "Fazer uma Doação",
    prayerWall: "Muro de Oração",
    howCanWePray: "Como Podemos",
    prayForYou: "Orar",
    forYouPrayer: "Por Você?",

    quickLinks: "Links Rápidos",
    contact: "Contato",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    allRightsReserved: "Todos os direitos reservados.",
    discover: "Descobrir",
    error: "Erro",
  },
  de: {
    welcome: "Willkommen bei CHub",
    home: "Startseite",
    sermons: "Predigten",
    events: "Veranstaltungen",
    prayer: "Gebet",
    devotionals: "Andachten",
    give: "Geben",
    live: "Live",
    music: "Musik",
    bible: "Bibelstudium",
    discipleship: "Jüngerschaft",
    login: "Anmelden",
    logout: "Abmelden",
    dashboard: "Dashboard",
    admin: "Admin",
    members: "Mitglieder",
    attendance: "Teilnahme",
    analytics: "Analytik",
    messages: "Nachrichten",
    profile: "Profil",
    settings: "Einstellungen",
    search: "Suchen...",
    learnMore: "Mehr Erfahren",
    serviceTimes: "Gottesdienstzeiten",
    sundayService: "Sonntagsgottesdienst",
    wednesdayService: "Mittwochsgottesdienst",
    location: "Standort",
    contactUs: "Kontaktieren Sie Uns",
    aboutUs: "Über Uns",
    recentSermons: "Aktuelle Predigten",
    upcomingEvents: "Kommende Veranstaltungen",
    prayerRequests: "Gebetsanfragen",
    donate: "Spenden",
    watchLive: "Live Ansehen",
    joinNow: "Jetzt Teilnehmen",
    readMore: "Mehr Lesen",
    viewAll: "Alle Ansehen",
    viewAllEvents: "Alle Veranstaltungen Ansehen",
    viewPastEvents: "Vergangene Veranstaltungen Ansehen",
    joinUsForFellowship: "Schließen Sie sich uns an für Gemeinschaft und Wachstum",
    noEvents: "Keine anstehenden Veranstaltungen",
    noSermons: "Keine Predigten verfügbar",
    volunteer: "Freiwillig",
    groups: "Gruppen",
    houseCells: "Hauskreise",
    media: "Medien",
    community: "Gemeinschaft",
    getStarted: "Loslegen",
    myDashboard: "Mein Dashboard",
    adminDashboard: "Admin Dashboard",
    myAttendance: "Meine Teilnahme",
    privacy: "Datenschutz",
    signOut: "Abmelden",
    feed: "Feed",

    welcomeToCHub: "Willkommen bei CHub",
    experienceThe: "Erleben Sie die",
    powerOfFaith: "Kraft des Glaubens",
    heroDescription: "Werden Sie Teil einer lebendigen Gemeinschaft, die sich dem Lieben Gottes und der Menschen widmet.",
    planAVisit: "Besuch Planen",
    watchOnline: "Online Ansehen",
    checkIn: "Einchecken",
    membersCount: "Mitglieder",
    yearsActive: "Aktive Jahre",
    ministries: "Dienste",
    latestSermons: "Neueste Predigten",
    getInvolved: "Mitmachen",
    ourMinistries: "Unsere Dienste",
    communityGroups: "Gemeinschaftsgruppen",
    bibleStudy: "Bibelstudium",
    prayerMinistry: "Gebetsdienst",
    visitUs: "Besuchen Sie Uns",
    visitUsThisSunday: "Besuchen Sie Uns Diesen Sonntag",
    getDirections: "Wegbeschreibung",

    welcomeBack: "Willkommen zurück",
    createYourAccount: "Erstellen Sie Ihr Konto",
    signIn: "Anmelden",
    createAccount: "Konto erstellen",
    signUp: "Registrieren",
    fullName: "Vollständiger Name",
    emailAddress: "E-Mail-Adresse",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",

    eventsCalendar: "Veranstaltungskalender",
    all: "Alle",
    allEvents: "Alle Veranstaltungen",
    sermonLibrary: "Predigtbibliothek",
    generosity: "Großzügigkeit",
    giveGenerously: "Geben Sie",
    generouslyHighlight: "Großzügig",
    makeADonation: "Spenden",
    prayerWall: "Gebetswand",
    howCanWePray: "Wie Können Wir",
    prayForYou: "Beten",
    forYouPrayer: "Für Sie?",

    quickLinks: "Schnelllinks",
    contact: "Kontakt",
    privacyPolicy: "Datenschutzrichtlinie",
    termsOfService: "Nutzungsbedingungen",
    allRightsReserved: "Alle Rechte vorbehalten.",
    discover: "Entdecken",
    error: "Fehler",
  },
  zh: {
    welcome: "欢迎来到CHub",
    home: "首页",
    sermons: "讲道",
    events: "活动",
    prayer: "祷告",
    devotionals: "灵修",
    give: "奉献",
    live: "直播",
    music: "音乐",
    bible: "圣经学习",
    discipleship: "门徒训练",
    login: "登录",
    logout: "退出",
    dashboard: "仪表板",
    admin: "管理",
    members: "成员",
    attendance: "出席",
    analytics: "分析",
    messages: "消息",
    profile: "个人资料",
    settings: "设置",
    search: "搜索...",
    learnMore: "了解更多",
    serviceTimes: "聚会时间",
    sundayService: "主日崇拜",
    wednesdayService: "周三聚会",
    location: "地点",
    contactUs: "联系我们",
    aboutUs: "关于我们",
    recentSermons: "最近讲道",
    upcomingEvents: "即将举行的活动",
    prayerRequests: "祷告请求",
    donate: "奉献",
    watchLive: "观看直播",
    joinNow: "立即参加",
    readMore: "阅读更多",
    viewAll: "查看全部",
    viewAllEvents: "查看所有活动",
    viewPastEvents: "查看过去的活动",
    joinUsForFellowship: "加入我们一起团契和成长",
    noEvents: "没有即将举行的活动",
    noSermons: "没有可用的讲道",
    volunteer: "志愿者",
    groups: "小组",
    houseCells: "家庭小组",
    media: "媒体",
    community: "社区",
    getStarted: "开始",
    myDashboard: "我的仪表板",
    adminDashboard: "管理仪表板",
    myAttendance: "我的出席",
    privacy: "隐私",
    signOut: "退出",
    feed: "动态",

    welcomeToCHub: "欢迎来到CHub",
    experienceThe: "体验",
    powerOfFaith: "信仰的力量",
    heroDescription: "加入一个充满活力的社区，致力于爱上帝、爱人们，并在我们的城市及更远的地方产生影响。",
    planAVisit: "计划访问",
    watchOnline: "在线观看",
    checkIn: "签到",
    membersCount: "成员",
    yearsActive: "活跃年数",
    ministries: "事工",
    latestSermons: "最新讲道",
    getInvolved: "参与",
    ourMinistries: "我们的事工",
    communityGroups: "社区小组",
    bibleStudy: "圣经学习",
    prayerMinistry: "祷告事工",
    visitUs: "访问我们",
    visitUsThisSunday: "本周日来访问我们",
    getDirections: "获取路线",

    welcomeBack: "欢迎回来",
    createYourAccount: "创建您的账户",
    signIn: "登录",
    createAccount: "创建账户",
    signUp: "注册",
    fullName: "全名",
    emailAddress: "电子邮件地址",
    password: "密码",
    forgotPassword: "忘记密码？",

    eventsCalendar: "活动日历",
    all: "全部",
    allEvents: "所有活动",
    sermonLibrary: "讲道库",
    generosity: "慷慨",
    giveGenerously: "慷慨",
    generouslyHighlight: "奉献",
    makeADonation: "捐赠",
    prayerWall: "祷告墙",
    howCanWePray: "我们如何",
    prayForYou: "为您",
    forYouPrayer: "祷告？",

    quickLinks: "快速链接",
    contact: "联系",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    allRightsReserved: "版权所有。",
    discover: "发现",
    error: "错误",
  },
  ar: {
    welcome: "مرحبا بك في CHub",
    home: "الرئيسية",
    sermons: "عظات",
    events: "أحداث",
    prayer: "صلاة",
    devotionals: "تأملات",
    give: "إعطاء",
    live: "بث مباشر",
    music: "موسيقى",
    bible: "دراسة الكتاب المقدس",
    discipleship: "التلمذة",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    dashboard: "لوحة التحكم",
    admin: "مدير",
    members: "أعضاء",
    attendance: "الحضور",
    analytics: "تحليلات",
    messages: "رسائل",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    search: "بحث...",
    learnMore: "اعرف المزيد",
    serviceTimes: "أوقات العبادة",
    sundayService: "خدمة الأحد",
    wednesdayService: "خدمة الأربعاء",
    location: "الموقع",
    contactUs: "اتصل بنا",
    aboutUs: "من نحن",
    recentSermons: "العظات الأخيرة",
    upcomingEvents: "الأحداث القادمة",
    prayerRequests: "طلبات الصلاة",
    donate: "تبرع",
    watchLive: "شاهد البث المباشر",
    joinNow: "انضم الآن",
    readMore: "اقرأ المزيد",
    viewAll: "عرض الكل",
    viewAllEvents: "عرض كل الأحداث",
    viewPastEvents: "عرض الأحداث السابقة",
    joinUsForFellowship: "انضم إلينا للعبادة والنمو",
    noEvents: "لا توجد أحداث قادمة",
    noSermons: "لا توجد عظات متاحة",
    volunteer: "متطوع",
    groups: "مجموعات",
    houseCells: "خلايا منزلية",
    media: "وسائط",
    community: "مجتمع",
    getStarted: "ابدأ",
    myDashboard: "لوحة التحكم",
    signOut: "تسجيل الخروج",
    feed: "الأخبار",

    welcomeToCHub: "مرحبا بك في CHub",
    experienceThe: "اختبر",
    powerOfFaith: "قوة الإيمان",
    planAVisit: "خطط لزيارة",
    watchOnline: "شاهد عبر الإنترنت",
    checkIn: "تسجيل الحضور",
    membersCount: "أعضاء",
    yearsActive: "سنوات نشطة",
    ministries: "خدمات",
    latestSermons: "أحدث العظات",
    getInvolved: "شارك",
    ourMinistries: "خدماتنا",
    communityGroups: "مجموعات مجتمعية",
    visitUs: "زرنا",
    visitUsThisSunday: "زرنا هذا الأحد",
    getDirections: "احصل على الاتجاهات",

    welcomeBack: "مرحبا بعودتك",
    createYourAccount: "أنشئ حسابك",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    signUp: "التسجيل",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",

    eventsCalendar: "تقويم الأحداث",
    all: "الكل",
    allEvents: "كل الأحداث",
    sermonLibrary: "مكتبة العظات",
    generosity: "الكرم",
    giveGenerously: "أعط",
    generouslyHighlight: "بسخاء",
    makeADonation: "قدم تبرعاً",
    prayerWall: "جدار الصلاة",
    howCanWePray: "كيف يمكننا",
    prayForYou: "نصلي",
    forYouPrayer: "من أجلك؟",

    quickLinks: "روابط سريعة",
    contact: "اتصل",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    allRightsReserved: "جميع الحقوق محفوظة.",
    discover: "اكتشف",
    error: "خطأ",
  },
  hi: {
    welcome: "CHub में आपका स्वागत है",
    home: "होम",
    sermons: "प्रचार",
    events: "कार्यक्रम",
    prayer: "प्रार्थना",
    devotionals: "आध्यात्मिक",
    give: "दान",
    live: "लाइव",
    music: "संगीत",
    bible: "बाइबल अध्ययन",
    discipleship: "शिष्यता",
    login: "लॉग इन",
    logout: "लॉग आउट",
    dashboard: "डैशबोर्ड",
    admin: "एडमिन",
    members: "सदस्य",
    attendance: "उपस्थिति",
    analytics: "विश्लेषण",
    messages: "संदेश",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    search: "खोजें...",
    learnMore: "और जानें",
    serviceTimes: "सेवा समय",
    sundayService: "रविवार सेवा",
    wednesdayService: "बुधवार सेवा",
    location: "स्थान",
    contactUs: "संपर्क करें",
    aboutUs: "हमारे बारे में",
    recentSermons: "हाल के प्रचार",
    upcomingEvents: "आगामी कार्यक्रम",
    prayerRequests: "प्रार्थना अनुरोध",
    donate: "दान करें",
    watchLive: "लाइव देखें",
    joinNow: "अभी शामिल हों",
    readMore: "और पढ़ें",
    viewAll: "सभी देखें",
    viewAllEvents: "सभी कार्यक्रम देखें",
    viewPastEvents: "पिछले कार्यक्रम देखें",
    joinUsForFellowship: "हमारे साथ भागीदारी और विकास के लिए शामिल हों",
    noEvents: "कोई आगामी कार्यक्रम नहीं",
    noSermons: "कोई प्रचार उपलब्ध नहीं",
    volunteer: "स्वयंसेवक",
    groups: "समूह",
    houseCells: "गृह कोशिकाएं",
    media: "मीडिया",
    community: "समुदाय",
    getStarted: "शुरू करें",
    myDashboard: "मेरा डैशबोर्ड",
    signOut: "साइन आउट",
    feed: "फ़ीड",

    welcomeToCHub: "CHub में आपका स्वागत है",
    experienceThe: "अनुभव करें",
    powerOfFaith: "विश्वास की शक्ति",
    planAVisit: "एक यात्रा की योजना बनाएं",
    watchOnline: "ऑनलाइन देखें",
    checkIn: "चेक इन",
    membersCount: "सदस्य",
    yearsActive: "सक्रिय वर्ष",
    ministries: "मंत्रालय",
    latestSermons: "नवीनतम प्रचार",
    getInvolved: "शामिल हों",
    ourMinistries: "हमारे मंत्रालय",
    communityGroups: "सामुदायिक समूह",
    visitUs: "हमसे मिलें",
    visitUsThisSunday: "इस रविवार हमसे मिलें",
    getDirections: "दिशा-निर्देश प्राप्त करें",

    welcomeBack: "वापसी पर स्वागत है",
    createYourAccount: "अपना खाता बनाएं",
    signIn: "साइन इन",
    createAccount: "खाता बनाएं",
    signUp: "साइन अप",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",

    eventsCalendar: "कार्यक्रम कैलेंडर",
    all: "सभी",
    allEvents: "सभी कार्यक्रम",
    sermonLibrary: "प्रचार पुस्तकालय",
    generosity: "उदारता",
    giveGenerously: "उदारता से",
    generouslyHighlight: "दान करें",
    makeADonation: "दान करें",
    prayerWall: "प्रार्थना दीवार",
    howCanWePray: "हम कैसे",
    prayForYou: "प्रार्थना",
    forYouPrayer: "करें आपके लिए?",

    quickLinks: "त्वरित लिंक",
    contact: "संपर्क",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    discover: "खोजें",
    error: "त्रुटि",
  },
  yo: {
    welcome: "Káàbọ̀ sí CHub",
    home: "Ìbẹ̀rẹ̀",
    sermons: "Ọ̀rọ̀",
    events: "Ìṣẹ̀lẹ̀",
    prayer: "Àdúrà",
    devotionals: "Ìwúyí",
    give: "Fún",
    live: "Lálà",
    music: "Orin",
    bible: "Ìwé Mímọ́",
    discipleship: "Ọmọ-ẹ̀hìn",
    login: "Ìwọlé",
    logout: "Ìpadà",
    dashboard: "Ọ̀pá",
    admin: "Oníṣàkóso",
    members: "Àwọn ọmọ́ ìjọ́",
    attendance: "Ẹsẹ̀",
    analytics: "Ìkójú",
    messages: "Ọ̀rọ̀",
    profile: "Àpẹẹrẹ",
    settings: "Ètò",
    search: "Wádìí...",
    learnMore: "Kọ́ Síi",
    serviceTimes: "Àkókò ìsìn",
    sundayService: "Ìsìn Ọ̀jọ́ Àìkú",
    wednesdayService: "Ìsìn Ọjọ́ Ẹ̀tà",
    location: "Ìpèsi",
    contactUs: "Pe wa",
    aboutUs: "Nípa wa",
    recentSermons: "Ọ̀rọ̀ tó ṣẹ̀ṣẹ̀",
    upcomingEvents: "Ìṣẹ̀lẹ̀ tó ń bọ̀",
    prayerRequests: "Ìbéèrè Àdúrà",
    donate: "Ìdójú",
    watchLive: "Wo Lálà",
    joinNow: "Darapọ̀ Báyìí",
    readMore: "Ka Púpọ̀",
    viewAll: "Wo Gbogbo",
    viewAllEvents: "Wo Gbogbo Ìṣẹ̀lẹ̀",
    viewPastEvents: "Wo Ìṣẹ̀lẹ̀ Àtijọ́",
    joinUsForFellowship: "Darapọ̀ mọ́ wa fún ìdàpọ̀ àti ìdàgbà",
    noEvents: "Kò sí ìṣẹ̀lẹ̀ kankan",
    noSermons: "Kò sí ọ̀rọ̀ kankan",
    volunteer: "Olùyọ̀ọ̀dá",
    groups: "Àwọn Ẹgbẹ́",
    houseCells: "Ẹgbẹ́ Ilé",
    media: "Àwọn Ohun Ìkànsí",
    community: "Àwùjọ",
    getStarted: "Bẹ̀rẹ̀",
    myDashboard: "Ọ̀pá Mi",
    signOut: "Jáde",
    feed: "Ìròyìn",

    welcomeToCHub: "Káàbọ̀ sí CHub",
    experienceThe: "Nírìí rí",
    powerOfFaith: "Agbára Ìgbàgbọ́",
    planAVisit: "Ṣètò Àbẹ̀wò",
    watchOnline: "Wo Lórí Ẹ̀rọ",
    checkIn: "Forúkọ Sílẹ̀",
    membersCount: "Àwọn Ọmọ Ẹgbẹ́",
    yearsActive: "Ọdún Tó Ti Pẹ́",
    ministries: "Àwọn Iṣẹ́",
    latestSermons: "Ọ̀rọ̀ Tuntun",
    getInvolved: "Kópa",
    ourMinistries: "Àwọn Iṣẹ́ Wa",
    communityGroups: "Àwọn Ẹgbẹ́ Àwùjọ",
    visitUs: "Ṣàbẹ̀wò",
    visitUsThisSunday: "Ṣàbẹ̀wò Ní Ọ̀jọ́ Àìkú Yìí",
    getDirections: "Gba Ìtọ́sọ́nà",

    welcomeBack: "Ẹ kú àbọ̀",
    createYourAccount: "Ṣẹ̀dá Àkọọ́lẹ̀ Rẹ",
    signIn: "Wọlé",
    createAccount: "Ṣẹ̀dá Àkọọ́lẹ̀",
    signUp: "Forúkọsílẹ̀",
    fullName: "Orúkọ Ní Kíkún",
    emailAddress: "Àdírẹ́sì Ímeèlì",
    password: "Ọ̀rọ̀ Aṣínà",
    forgotPassword: "Ọ̀rọ̀ aṣínà gbàgbé?",

    eventsCalendar: "Kàlẹ́ndà Ìṣẹ̀lẹ̀",
    all: "Gbogbo",
    allEvents: "Gbogbo Ìṣẹ̀lẹ̀",
    sermonLibrary: "Ilé Ìkàwé Ọ̀rọ̀",
    generosity: "Ọ̀lá-àánú",
    giveGenerously: "Fún",
    generouslyHighlight: "Lọ́pọ̀lọ́pọ̀",
    makeADonation: "Ṣe Ẹ̀bùn",
    prayerWall: "Ògiri Àdúrà",
    howCanWePray: "Báwo Ni A Ṣe Lè",
    prayForYou: "Gbàdúrà",
    forYouPrayer: "Fún Ẹ?",

    quickLinks: "Àwọn Ìtọ́ka",
    contact: "Kàn Sí Wa",
    privacyPolicy: "Ètò Àṣírí",
    termsOfService: "Àwọn Òfin Iṣẹ́",
    allRightsReserved: "Gbogbo ẹ̀tọ́ ni a dáàbò bò.",
    discover: "Ṣàwárí",
    error: "Àṣìṣe",
  },
};

const languages = [
  { code: "en" as Language, name: "English", nativeName: "English" },
  { code: "es" as Language, name: "Spanish", nativeName: "Español" },
  { code: "fr" as Language, name: "French", nativeName: "Français" },
  { code: "pt" as Language, name: "Portuguese", nativeName: "Português" },
  { code: "de" as Language, name: "German", nativeName: "Deutsch" },
  { code: "zh" as Language, name: "Chinese", nativeName: "中文" },
  { code: "ar" as Language, name: "Arabic", nativeName: "العربية" },
  { code: "hi" as Language, name: "Hindi", nativeName: "हिन्दी" },
  { code: "yo" as Language, name: "Yoruba", nativeName: "Yorùbá" },
];

const supportedTimezones = [
  "UTC",
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/Toronto",
  "America/Sao_Paulo",
  "Europe/London",
  "Europe/Paris",
  "Europe/Berlin",
  "Africa/Lagos",
  "Africa/Nairobi",
  "Asia/Dubai",
  "Asia/Singapore",
  "Asia/Tokyo",
  "Asia/Shanghai",
  "Australia/Sydney",
];

const supportedCurrencies = [
  "USD",
  "EUR",
  "GBP",
  "NGN",
  "KES",
  "ZAR",
  "BRL",
  "CAD",
  "AUD",
  "JPY",
  "CNY",
  "INR",
];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [preferences, setPreferences] = useState<UserPreferences>({
    preferredLanguage: "en",
    timezone: "UTC",
    currency: "USD",
  });
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
    
    const token = localStorage.getItem("token");
    setIsLoggedIn(!!token);
  }, []);

  useEffect(() => {
    if (isLoggedIn) {
      fetchUserPreferences();
    }
  }, [isLoggedIn]);

  const fetchUserPreferences = async () => {
    try {
      const token = localStorage.getItem("token");
      const response = await fetch("/api/user/preferences/language", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      if (response.ok) {
        const data = await response.json();
        setPreferences(data);
        if (data.preferredLanguage && translations[data.preferredLanguage as Language]) {
          setLanguageState(data.preferredLanguage as Language);
        }
      }
    } catch (error) {
      console.error("Failed to fetch user preferences:", error);
    }
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const updatePreferences = async (prefs: Partial<UserPreferences>) => {
    try {
      const token = localStorage.getItem("token");
      const response = await fetch("/api/user/preferences/language", {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(prefs),
      });
      if (response.ok) {
        const updated = await response.json();
        setPreferences(updated);
        if (updated.preferredLanguage && translations[updated.preferredLanguage as Language]) {
          setLanguageState(updated.preferredLanguage as Language);
        }
      }
    } catch (error) {
      console.error("Failed to update preferences:", error);
      throw error;
    }
  };

  const t = useCallback((key: string): string => {
    const langTranslations = translations[language];
    const result = langTranslations?.[key] || translations.en?.[key] || key;
    return result;
  }, [language]);

  const value = useMemo(() => ({ 
    language, 
    setLanguage, 
    t, 
    languages, 
    preferences,
    updatePreferences,
    supportedTimezones,
    supportedCurrencies,
  }), [language, t, preferences]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
